### ISSUE TITLE
 Node 10 EOL

### ISSUE THREAD

**Issue by hugosenari** [nearst/laconia#747]
**Describe the bug**

Node 10 are reaching EOL, [AWS will deprecate it](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html)

**Expected behavior**
Acceptance Tests and Circleci shouldn't run Node 10 anymore

**Additional context**
We could also look for code improvements with new ES features available at Node 12.
Ie:

- Array.prototype.values;
- Array.prototype.flat
- Array.prototype.flatMap
- Object.fromEntries
- Private class fields

**TODO**:
- [ ] Update serverless.yml
- [ ] Update package.json
- [ ] Update circleci/config.yml
- [ ] Update examples
- [ ]  Update `.nvmrc`

see also #419 and #657

**Comment by tschoffelen** [comment]
Tests have been updated to run on node 16 to 20, and the acceptance test runs on node 20 now.
